# Generated by Django 4.1.3 on 2022-11-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('request_manage', 'Can view and process users requests'), ('share_manage', 'Can view and process users shares'))},
        ),
    ]
