# Generated by Django 4.0.8 on 2022-10-12 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('plants_amount', models.IntegerField(default=0)),
                ('thing_amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RequestThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Shipped', 'Shipped')], default='Requested', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('plants_amount', models.IntegerField(default=0)),
                ('thing_amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ShareThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Tree', 'Tree'), ('Bush', 'Bush'), ('Flower', 'Used')], max_length=10)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField(db_column='latitude')),
                ('long', models.FloatField(db_column='longitude')),
                ('thing_count', models.IntegerField(default=0, null=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SharingPlant',
            fields=[
                ('sharething_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sharing.sharething')),
                ('common_details', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('video', models.FileField(blank=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            options={
                'abstract': False,
            },
            bases=('sharing.sharething',),
        ),
        migrations.CreateModel(
            name='SharingTool',
            fields=[
                ('sharething_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sharing.sharething')),
                ('common_details', models.CharField(max_length=200)),
                ('photo', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'abstract': False,
            },
            bases=('sharing.sharething',),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(check=models.Q(('thing_count__lte', django.db.models.expressions.F('capacity'))), name='thing_count_lte'),
        ),
        migrations.AddField(
            model_name='sharething',
            name='share_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.share'),
        ),
        migrations.AddField(
            model_name='sharething',
            name='warehouse_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.warehouse'),
        ),
        migrations.AddField(
            model_name='requestthing',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.request'),
        ),
        migrations.AddField(
            model_name='requestthing',
            name='warehouse_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.warehouse'),
        ),
        migrations.AddField(
            model_name='sharingplant',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.typeplant'),
        ),
    ]
