# Generated by Django 4.0.8 on 2022-10-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting', models.CharField(max_length=10)),
                ('watering', models.CharField(max_length=20)),
                ('transplant', models.CharField(max_length=40)),
                ('temperature', models.CharField(max_length=20)),
                ('growing_difficulty', models.CharField(choices=[('Low', 'requires constant monitoring'), ('Medium', 'requires care 1 time in 1-2 weeks'), ('High', 'requires care 1 time in 2-3 weeks')], default='Requested', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sharingplant',
            name='care',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.careplant'),
        ),
    ]
