# Generated by Django 4.0.8 on 2022-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(default='Minsk', max_length=20),
        ),
    ]
