# Generated by Django 4.0.8 on 2022-10-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_request_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
