# Generated by Django 4.1.3 on 2022-11-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
