# Generated by Django 4.1.3 on 2022-11-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_alter_request_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': (('request_manage', 'Can view and process users requests'),)},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'permissions': (('share_manage', 'Can view and process users shares'),)},
        ),
    ]
