# Generated by Django 4.1.3 on 2022-11-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_video_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('duration', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='year',
        ),
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharing.audio'),
        ),
    ]
