# Generated by Django 4.1.3 on 2022-11-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_remove_video_audio_video_frames_video_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='year',
        ),
        migrations.AddField(
            model_name='video',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='frames',
            field=models.FloatField(null=True),
        ),
    ]
