# Generated by Django 4.1.3 on 2022-11-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_remove_video_year_video_rate_alter_video_frames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='plant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharing.plant'),
        ),
    ]
