# Generated by Django 4.1.3 on 2022-11-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_alter_video_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careplant',
            name='growing_difficulty',
            field=models.CharField(choices=[('Low', 'requires constant monitoring'), ('Medium', 'requires care 1 time in 1-2 weeks'), ('High', 'requires care 1 time in 2-3 weeks')], default='Low', max_length=100),
        ),
    ]
